version: '3.8'

services:
  ad-app:
    build:
      context: ./WikiDotNet
      dockerfile: Dockerfile
    ports:
      - "5186:5186"
  service-discovery:
    build:
      context: ./eurekaDiscovery
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
      - "5007:5007"
  apigateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8083/eureka
    ports:
      - "8082:8082"
      - "5006:5006"
    depends_on:
        - service-discovery
  login:
    build:
      context: ./login
      dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8083/eureka
    ports:
      - "8080:8080"
      - "5008:5008"
    depends_on:
      - service-discovery
  audit-service:
    build:
      context: ./userChanges
      dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8083/eureka
    ports:
      - "8081:8081"
    depends_on:
      - service-discovery
  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "4200:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: